name: stevio-os
description: This is my personal OS image.

base-image: ghcr.io/wayblueorg/hyprland
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos: {}
    install: {}
    remove: {}

  - type: default-flatpaks
    notify: true
    system:
      install: {}
      remove: {}
      user: {}

  - type: signing
