---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: stevio-os
description: This is my personal OS image.

base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 41-aarch64

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos: []
    install: []
    remove: []

  - type: default-flatpaks
    notify: true
    system:
      install: []
      remove: []
      user: {}

  - type: signing
