#!/usr/bin/sh

getent group greetd > /dev/null || groupadd -r greetd
getent passwd greetd > /dev/null || useradd -r -g greetd -c "Greetd Greeter Account" -d /var/lib/gtkgreet -s /usr/sbin/nologin greetd
