# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
modules:
  - type: dnf
    install:
      packages:
        - firefox
        - foot
        - neovim
        - just
        - git
      exclude:
        - alacritty
