# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
modules:
  - type: dnf
    repos:
      files:
        add:
          - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%OS_VERSION%/solopasha-hyprland-fedora-%OS_VERSION%.repo
          - https://copr.fedorainfracloud.org/coprs/erikreider/SwayNotificationCenter/repo/fedora-%OS_VERSION%/erikreider-SwayNotificationCenter-fedora-%OS_VERSION%.repo
      # copr:
      #   enable:
      #     - solopasha/hyprland
      #     - erikreider/SwayNotificationCenter
    install:
      install-weak-deps: false
      packages:
        - repo: solopasha-hyprland-fedora-%OS_VERSION%
          packages:
            - hyprland
            - hyprpolkitagent
            - xdg-desktop-portal-hyprland
        - repo: erikreider-SwayNotificationCenter-fedora-%OS_VERSION%
          packages:
            - SwayNotificationCenter
        - pipewire
        - wireplumber
        - qt5-wayland
        - qt6-wayland
        - xdg-user-dirs
