# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
modules:
  - type: dnf
    repos:
      copr:
        enable:
          - solopasha/hyprland
          - erikreider/SwayNotificationCenter
    install:
      install-weak-deps: false
      packages:
        - hyprland
        - hyprpolkitagent
        - xdg-desktop-portal-hyprland
        - SwayNotificationCenter
        - pipewire
        - wireplumber
        - qt5-qtwayland
        - qt6-qtwayland
        - xdg-user-dirs
        - slurp
        - grim
