# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
modules:
  - type: rpm-ostree
    install:
      - pipewire
      - wireplumber
      - qt5-qtwayland
      - qt6-qtwayland
      - xdg-user-dirs
